/**
 * AuthenX Connector — Cryptographic Engine
 *
 * This is the most security-critical module in the connector.
 * Handles:
 *  - SHA-256 hashing of canonical fingerprints
 *  - Ed25519 signing of issued hashes and live verification responses
 *  - Loading and validating the college private key
 *
 * SECURITY RULES:
 *  - Private key NEVER leaves this module
 *  - Private key NEVER goes into logs
 *  - Private key is loaded once at startup and kept in memory
 *  - All signing happens here — no other module touches the key
 */

import crypto from 'crypto';
import nacl from 'tweetnacl';

// ─── Private Key Management ───────────────────────────────────────────────────

let _privateKey: Uint8Array | null = null;
let _publicKey: Uint8Array | null = null;

/**
 * Loads and validates the college Ed25519 private key from environment.
 * Must be called once at connector startup.
 *
 * The private key is the full 64-byte Ed25519 secret key (hex-encoded).
 * This is generated by: npm run keygen
 */
export function loadPrivateKey(privateKeyHex: string): void {
  if (!privateKeyHex || privateKeyHex.length !== 128) {
    throw new Error(
      'Invalid COLLEGE_PRIVATE_KEY: must be 128 hex chars (64 bytes Ed25519 secret key). ' +
      'Generate with: npm run keygen'
    );
  }

  const keyBytes = Buffer.from(privateKeyHex, 'hex');
  _privateKey = new Uint8Array(keyBytes);

  // Derive the public key from the private key (for verification / sanity check)
  const keyPair = nacl.sign.keyPair.fromSecretKey(_privateKey);
  _publicKey = keyPair.publicKey;

  console.log('🔑 Connector crypto: Ed25519 key loaded successfully');
  console.log(`   Public key (register this with AuthenX): ${Buffer.from(_publicKey).toString('hex')}`);
}

/**
 * Returns the college's Ed25519 public key as hex.
 * Share this with AuthenX at onboarding.
 */
export function getPublicKeyHex(): string {
  if (!_publicKey) throw new Error('Private key not loaded. Call loadPrivateKey() first.');
  return Buffer.from(_publicKey).toString('hex');
}

// ─── SHA-256 Hash ─────────────────────────────────────────────────────────────

/**
 * Computes SHA-256 of a string. Returns lowercase hex.
 */
export function sha256(input: string): string {
  return crypto.createHash('sha256').update(input, 'utf8').digest('hex');
}

// ─── Ed25519 Signing ──────────────────────────────────────────────────────────

/**
 * Signs a message with the college's Ed25519 private key.
 * Returns base64-encoded signature.
 *
 * @param message - String to sign (e.g., issued_hash or response JSON)
 */
export function sign(message: string): string {
  if (!_privateKey) throw new Error('Private key not loaded');

  const messageBytes = new Uint8Array(Buffer.from(message, 'utf8'));
  const signature = nacl.sign.detached(messageBytes, _privateKey);
  return Buffer.from(signature).toString('base64');
}

/**
 * Generates an issuance signature over the canonical hash.
 * This is the FIRST signature — proves "we issued this credential."
 */
export function signIssuance(canonicalHash: string): string {
  return sign(canonicalHash);
}

/**
 * Generates a live verification signature over the full response payload.
 * This is the SECOND signature — proves "we confirm it NOW."
 *
 * The payload must include the nonce to bind it to this specific request.
 */
export function signVerificationResponse(responsePayload: object): string {
  return sign(JSON.stringify(responsePayload));
}
